# Generated by Django 2.2.2 on 2019-10-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountRecList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReconciliationListThresholds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollarValueThreshold', models.CharField(default=0, max_length=200)),
                ('percentValueThreshold', models.CharField(default=0, max_length=200)),
            ],
        ),
    ]
