# Generated by Django 2.2.2 on 2019-10-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountRecList', '0002_accountreconciliationlistthresholds'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreconciliationlistthresholds',
            name='excludedAccounts',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
