# Generated by Django 2.2.2 on 2019-10-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountRecList', '0003_accountreconciliationlistthresholds_excludedaccounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountreconciliationlist',
            name='approvalStatus_Description',
        ),
    ]
