# Generated by Django 2.2.2 on 2019-10-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountRecList', '0004_remove_accountreconciliationlist_approvalstatus_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreconciliationlist',
            name='accountBalanceReconciled',
            field=models.IntegerField(default=0, max_length=200),
        ),
    ]
