# Generated by Django 2.2.2 on 2019-10-02 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userDefinedEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(default='Select Entity', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='userDefinedTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=200)),
                ('entity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='entity_userDefinedTeam', to='CompanyMaintain.userDefinedEntity')),
                ('teamOwner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_teamOwner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userReviewerMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemIdentifier', models.CharField(max_length=200)),
                ('entity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='entity_userReviewerMapping', to='CompanyMaintain.userDefinedEntity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_user', to=settings.AUTH_USER_MODEL)),
                ('userManager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_Manager', to=settings.AUTH_USER_MODEL)),
                ('userReviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_Reviewer', to=settings.AUTH_USER_MODEL)),
                ('userTeam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_team', to='CompanyMaintain.userDefinedTeam')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userreviewermapping',
            constraint=models.UniqueConstraint(fields=('user', 'entity'), name='unique_EntityUser'),
        ),
        migrations.AddConstraint(
            model_name='userdefinedteam',
            constraint=models.UniqueConstraint(fields=('team', 'entity'), name='unique_EntityTeam'),
        ),
    ]
