# Generated by Django 2.2.2 on 2020-01-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCheckList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskchecklist',
            name='taskPeriod',
            field=models.IntegerField(choices=[('Opened', 'Opened'), ('Closed', 'Closed'), ('Late Entry', 'Late Entry')], max_length=2),
        ),
    ]
