# Generated by Django 2.2.2 on 2019-06-13 20:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userDefinedEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(default='Select Entity', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='userDefinedTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=200)),
                ('entity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='entity_userDefinedTeam', to='CloseApplication.userDefinedEntity')),
                ('teamOwner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_teamOwner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userReviewerMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemIdentifier', models.CharField(max_length=200)),
                ('entity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='entity_userReviewerMapping', to='CloseApplication.userDefinedEntity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_user', to=settings.AUTH_USER_MODEL)),
                ('userManager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_Manager', to=settings.AUTH_USER_MODEL)),
                ('userReviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_Reviewer', to=settings.AUTH_USER_MODEL)),
                ('userTeam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_team', to='CloseApplication.userDefinedTeam')),
            ],
        ),
        migrations.CreateModel(
            name='TaskChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.CharField(max_length=8)),
                ('taskTBMapping', models.CharField(default='Not Assigned', max_length=200)),
                ('taskDescription', models.CharField(max_length=200)),
                ('taskYear', models.IntegerField(max_length=4)),
                ('taskPeriod', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], max_length=2)),
                ('taskOccurence', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('A', 'Annually')], max_length=2)),
                ('taskStatus', models.CharField(choices=[('NS', 'Not Started'), ('WT', 'Waiting on Preceding Task'), ('IP', 'In-Progress'), ('CT', 'Completed')], max_length=2)),
                ('isJE', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('due_date', models.DateField(default=datetime.date.today, verbose_name='Due Date')),
                ('entity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='entity_TaskChecklist', to='CloseApplication.userDefinedEntity')),
                ('taskOwnerId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='subTaskChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTaskNumber', models.IntegerField(default=1, max_length=2)),
                ('subTaskDescription', models.CharField(max_length=200)),
                ('subTaskStatus', models.CharField(choices=[('NS', 'Not Started'), ('WT', 'Waiting on Preceding Task'), ('IP', 'In-Progress'), ('CT', 'Completed')], max_length=2)),
                ('taskId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskId_taskId', to='CloseApplication.TaskChecklist')),
            ],
        ),
        migrations.CreateModel(
            name='journalEntryApprovalList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryNumber', models.CharField(max_length=200)),
                ('entryReference', models.CharField(max_length=200)),
                ('entryDescription', models.CharField(max_length=200)),
                ('postingDate', models.DateTimeField(verbose_name='date posted to GL')),
                ('entryReversed', models.BooleanField(default=False)),
                ('reversalNumber', models.CharField(blank=True, max_length=200)),
                ('postingUsername', models.CharField(max_length=200)),
                ('supportStatus', models.BooleanField(default=False)),
                ('approvalStatus', models.BooleanField(default=False)),
                ('approvalStatus_Description', models.CharField(choices=[('Not Started', 'Not Started'), ('Waiting on Support', 'Waiting on Support Upload'), ('Rejected', 'In-Progress'), ('Reverted', 'In-Progress'), ('Approved', 'Completed')], max_length=200)),
                ('approverComments', models.CharField(blank=True, max_length=200)),
                ('entity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='entity_journalEntryApprovalList', to='CloseApplication.userDefinedEntity')),
            ],
        ),
        migrations.CreateModel(
            name='AccountReconciliationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(max_length=50)),
                ('accountDescription', models.CharField(max_length=200)),
                ('accountBalance', models.IntegerField(default=0, max_length=200)),
                ('reconciliationYear', models.IntegerField(max_length=4)),
                ('reconciliationPeriod', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], max_length=2)),
                ('reconciliationStatus', models.CharField(choices=[('NS', 'Not Started'), ('WT', 'Waiting on Preceding Task'), ('IP', 'In-Progress'), ('CT', 'Completed')], max_length=2)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('due_date', models.DateField(default=datetime.date.today, verbose_name='Due Date')),
                ('entity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='entity_AccountReconciliationList', to='CloseApplication.userDefinedEntity')),
                ('reconciliationOwnerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userreviewermapping',
            constraint=models.UniqueConstraint(fields=('user', 'entity'), name='unique_EntityUser'),
        ),
        migrations.AddConstraint(
            model_name='userdefinedteam',
            constraint=models.UniqueConstraint(fields=('team', 'entity'), name='unique_EntityTeam'),
        ),
    ]
