# Generated by Django 2.1.7 on 2019-04-06 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CloseApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReconciliationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(max_length=50)),
                ('accountDescription', models.CharField(max_length=200)),
                ('reconciliationYear', models.IntegerField(max_length=4)),
                ('reconciliationPeriod', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], max_length=2)),
                ('reconciliationStatus', models.CharField(choices=[('NS', 'Not Started'), ('WT', 'Waiting on Preceding Task'), ('IP', 'In-Progress'), ('CT', 'Completed')], max_length=2)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('reconciliationOwnerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
