# Generated by Django 2.2.2 on 2019-06-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloseApplication', '0002_accountreconciliationlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreconciliationlist',
            name='entity',
            field=models.CharField(default='Select Entity', max_length=200),
        ),
        migrations.AddField(
            model_name='taskchecklist',
            name='entity',
            field=models.CharField(default='Select Entity', max_length=200),
        ),
    ]
