# Generated by Django 2.2.2 on 2019-06-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloseApplication', '0002_remove_journalentryapprovallist_entrynumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryapprovallist',
            name='entryNumber',
            field=models.CharField(default=10010011, max_length=200),
            preserve_default=False,
        ),
    ]
