# Generated by Django 2.2.2 on 2019-06-13 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CloseApplication', '0003_journalentryapprovallist_entrynumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentryapprovallist',
            name='entity',
        ),
    ]
