# Generated by Django 2.2.2 on 2019-06-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloseApplication', '0003_auto_20190605_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreconciliationlist',
            name='accountBalance',
            field=models.IntegerField(default=0, max_length=200),
        ),
    ]
