# Generated by Django 2.2.2 on 2019-06-05 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloseApplication', '0004_accountreconciliationlist_accountbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='journalEntryApprovalList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(default='Select Entity', max_length=200)),
                ('entryNumber', models.CharField(max_length=200)),
                ('entryReference', models.CharField(max_length=200)),
                ('entryDescription', models.CharField(max_length=200)),
                ('postingDate', models.DateTimeField(verbose_name='date posted to GL')),
                ('entryReversed', models.BooleanField(default=False)),
                ('reversalNumber', models.CharField(default=None, max_length=200)),
                ('postingUsername', models.CharField(max_length=200)),
                ('postingReviewer', models.CharField(max_length=200)),
                ('supportStatus', models.BooleanField(default=False)),
                ('approvalStatus', models.BooleanField(default=False)),
                ('approvalStatus_Description', models.CharField(choices=[('Not Started', 'Not Started'), ('Waiting on Support', 'Waiting on Support Upload'), ('Rejected', 'In-Progress'), ('Reverted', 'In-Progress'), ('Approved', 'Completed')], max_length=200)),
                ('approverComments', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='accountreconciliationlist',
            name='due_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='taskchecklist',
            name='due_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Due Date'),
        ),
    ]
