# Generated by Django 2.2.2 on 2019-06-13 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CloseApplication', '0004_remove_journalentryapprovallist_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryapprovallist',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='entity_journalEntryApprovalList', to='CloseApplication.userDefinedEntity'),
        ),
    ]
