# Generated by Django 2.2.2 on 2019-06-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloseApplication', '0005_journalentryapprovallist_entity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taskchecklist',
            constraint=models.UniqueConstraint(fields=('taskId', 'entity'), name='unique_EntityUser'),
        ),
    ]
