# Generated by Django 2.2.2 on 2019-06-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CloseApplication', '0005_auto_20190605_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
