# Generated by Django 2.2.2 on 2019-06-06 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CloseApplication', '0006_auto_20190605_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='userDefinedTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=200)),
                ('teamOwner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_teamOwner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='taskchecklist',
            name='taskOwnerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='userReviewerMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemIdentifier', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_user', to=settings.AUTH_USER_MODEL)),
                ('userManager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_Manager', to=settings.AUTH_USER_MODEL)),
                ('userReviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_Reviewer', to=settings.AUTH_USER_MODEL)),
                ('userTeam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_team', to='CloseApplication.userDefinedTeam')),
            ],
        ),
    ]
