# Generated by Django 2.2.2 on 2019-06-14 04:10

import CloseApplication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloseApplication', '0006_auto_20190613_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreconciliationlist',
            name='docfile',
            field=models.FileField(default=False, upload_to=CloseApplication.models.AccountReconciliationList.File_Path),
        ),
    ]
