# Generated by Django 2.2.2 on 2019-06-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloseApplication', '0007_auto_20190606_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskchecklist',
            name='subTaskNumber',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='taskchecklist',
            name='taskId',
            field=models.CharField(max_length=8),
        ),
    ]
