# Generated by Django 2.2.2 on 2019-06-14 19:05

import CloseApplication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloseApplication', '0007_accountreconciliationlist_docfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryapprovallist',
            name='docfile',
            field=models.FileField(default=False, upload_to=CloseApplication.models.journalEntryApprovalList.File_Path),
        ),
    ]
