# Generated by Django 2.2.2 on 2019-06-16 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CloseApplication', '0008_journalentryapprovallist_docfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskchecklist',
            name='taskStatus',
        ),
    ]
