# Generated by Django 2.2.2 on 2019-06-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloseApplication', '0008_auto_20190606_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskchecklist',
            name='taskTBMapping',
            field=models.CharField(default='Not Assigned', max_length=200),
        ),
    ]
