# Generated by Django 2.2.2 on 2019-06-07 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CloseApplication', '0009_taskchecklist_tasktbmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskchecklist',
            name='subTaskNumber',
        ),
        migrations.CreateModel(
            name='subTaskChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTaskNumber', models.IntegerField(default=1, max_length=2)),
                ('subTaskDescription', models.CharField(max_length=200)),
                ('subTaskStatus', models.CharField(choices=[('NS', 'Not Started'), ('WT', 'Waiting on Preceding Task'), ('IP', 'In-Progress'), ('CT', 'Completed')], max_length=2)),
                ('taskId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskId_taskId', to='CloseApplication.TaskChecklist')),
            ],
        ),
    ]
