# Generated by Django 2.2.2 on 2019-06-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloseApplication', '0010_auto_20190617_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskchecklist',
            name='dueMonth',
            field=models.IntegerField(default=6, max_length=2),
        ),
        migrations.AddField(
            model_name='taskchecklist',
            name='dueMonthDay',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='taskchecklist',
            name='dueYear',
            field=models.IntegerField(default=2019, max_length=4),
        ),
    ]
