# Generated by Django 2.2.2 on 2019-06-22 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CloseApplication', '0011_auto_20190622_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskchecklist',
            name='dueMonth',
        ),
        migrations.RemoveField(
            model_name='taskchecklist',
            name='dueYear',
        ),
    ]
