# Generated by Django 2.2.2 on 2019-06-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloseApplication', '0012_auto_20190622_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskchecklist',
            name='taskOccurence',
            field=models.CharField(choices=[('M', 'Monthly'), ('Q', 'Quarterly'), ('S', 'Semi-Annually'), ('A', 'Annually')], max_length=2),
        ),
    ]
