# Generated by Django 2.2.2 on 2019-06-26 18:33

import CloseApplication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloseApplication', '0013_auto_20190622_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtaskchecklist',
            name='docfile',
            field=models.FileField(default=False, upload_to=CloseApplication.models.subTaskChecklist.File_Path),
        ),
    ]
