# Generated by Django 2.2.2 on 2019-09-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloseApplication', '0014_subtaskchecklist_docfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreconciliationlist',
            name='approvalStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountreconciliationlist',
            name='approvalStatus_Description',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Waiting on Support', 'Waiting on Support Upload'), ('Rejected', 'In-Progress'), ('Reverted', 'In-Progress'), ('Approved', 'Completed')], default='Not Started', max_length=200),
        ),
        migrations.AddField(
            model_name='accountreconciliationlist',
            name='approverComments',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='subtaskchecklist',
            constraint=models.UniqueConstraint(fields=('taskId', 'subTaskNumber'), name='unique_Subtask'),
        ),
    ]
