# Generated by Django 2.2.2 on 2019-10-02 23:05

import JournalEntryList.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CompanyMaintain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='journalEntryApprovalList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryNumber', models.CharField(max_length=200)),
                ('entryReference', models.CharField(max_length=200)),
                ('entryDescription', models.CharField(max_length=200)),
                ('postingDate', models.DateTimeField(verbose_name='date posted to GL')),
                ('entryReversed', models.BooleanField(default=False)),
                ('reversalNumber', models.CharField(blank=True, max_length=200)),
                ('postingUsername', models.CharField(max_length=200)),
                ('supportStatus', models.BooleanField(default=False)),
                ('approvalStatus', models.BooleanField(default=False)),
                ('approvalStatus_Description', models.CharField(choices=[('Not Started', 'Not Started'), ('Waiting on Support', 'Waiting on Support Upload'), ('Rejected', 'In-Progress'), ('Reverted', 'In-Progress'), ('Approved', 'Completed')], max_length=200)),
                ('approverComments', models.CharField(blank=True, max_length=200)),
                ('docfile', models.FileField(default=False, upload_to=JournalEntryList.models.journalEntryApprovalList.File_Path)),
                ('entity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='entity_journalEntryApprovalList', to='CompanyMaintain.userDefinedEntity')),
            ],
        ),
    ]
